language: python
python:
  - "2.7"

before_script:
  - export CLAY_CONFIG=config/travis.json
  - make bootstrap_db

  
# command to install dependencies
install:
  - make bootstrap

# command to run tests
script: make test

services:
  - redis-server
