language: python
python:
  - "2.7"

before_script:
  - export CLAY_CONFIG=config/travis.json
  - redis-server &
  - make bootstrap_db

  
# command to install dependencies
install:
  - make bootstrap
  - wget http://download.redis.io/redis-stable.tar.gz
  - tar xvzf redis-stable.tar.gz
  - cd redis-stable
  - make
  - cp src/redis-cli /usr/local/bin/
  - cp src/redis-server /usr/local/bin/
  - cd ..
  - rm redis-stable.tar.gz

# command to run tests
script: make test

